version: "2"

services:
  ### postgresql
  postgres:
    image: postgres:13-alpine
    container_name:
      docker_postgres_1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sonarqube
    volumes:
      - $PATH_WWW_DATA/postgresql:/var/lib/postgresql/data

  ### sonarqube
  sonarqube:
#    image: sonarqube:8.2-community
    image: raw34/sonarqube
    container_name:
      docker_sonarqube_1
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 1
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: 123456
    volumes:
      - $PATH_WWW_LOG/sonarqube:/opt/sonarqube/logs
      - $PATH_WWW_DATA/sonarqube:/opt/sonarqube/data
    links:
      - postgres
